export const PET_CREATION_STARTED = "PET_CREATION_STARTED";
export const PET_CREATION_SUCCESS = "PET_CREATION_SUCCESS";
export const PET_CREATION_FAILED = "PET_CREATION_FAILED";

export const PET_DETAILS_SUCCESS = "PET_DETAILS_SUCCESS";
export const PET_DETAILS_STARTED = "PET_DETAILS_STARTED";
export const PET_DETAILS_FAILED = "PET_DETAILS_FAILED";

export const PET_FETCH_STARTED = "PETS_FETCH_STARTED";
export const PET_FETCH_SUCCESS = "PETS_FETCH_SUCCESS";
export const PET_FETCH_FAILED = "PETS_FETCH_FAILED";

export const PET_UPDATE_STARTED = "PETS_UPDATE_STARTED";
export const PET_UPDATE_SUCCESS = "PETS_UPDATE_SUCCESS";
export const PET_UPDATE_FAILED = "PETS_UPDATE_FAILED";

export const PET_DELETE_STARTED = "PETS_DELETE_STARTED";
export const PET_DELETE_SUCCESS = "PETS_DELETE_SUCCESS";
export const PET_DELETE_FAILED = "PETS_DELETE_FAILED";
