export const NOTIF_CREATION_SUCCESS = "NOTIF_CREATION_SUCCESS";
export const NOTIF_CREATION_STARTED = "NOTIF_CREATION_STARTED";
export const NOTIF_CREATION_FAILED = "NOTIF_CREATION_FAILED";

export const NOTIF_DETAILS_SUCCESS = "NOTIF_DETAILS_SUCCESS";
export const NOTIF_DETAILS_STARTED = "NOTIF_DETAILS_STARTED";
export const NOTIF_DETAILS_FAILED = "NOTIF_DETAILS_FAILED";

export const NOTIF_FETCH_SUCCESS = "NOTIF_FETCH_SUCCESS";
export const NOTIF_FETCH_STARTED = "NOTIF_FETCH_STARTED";
export const NOTIF_FETCH_FAILED = "NOTIF_FETCH_FAILED";

export const NOTIF_UPDATE_SUCCESS = "NOTIF_UPDATE_SUCCESS";
export const NOTIF_UPDATE_FAILED = "NOTIF_UPDATE_FAILED";
export const NOTIF_UPDATE_STARTED = "NOTIF_UPDATE_STARTED";

export const NOTIF_DELETE_SUCCESS = "NOTIF_DELETE_SUCCESS";
export const NOTIF_DELETE_STARTED = "NOTIF_DELETE_STARTED";
export const NOTIF_DELETE_FAILED = "NOTIF_DELETE_FAILED";
