export const ALERT_CREATION_STARTED = "ALERT_CREATION_STARTED";
export const ALERT_CREATION_SUCCESS = "ALERT_CREATION_SUCCESS";
export const ALERT_CREATION_FAILED = "ALERT_CREATION_FAILED";

export const ALERT_DETAILS_SUCCESS = "ALERT_DETAILS_SUCCESS";
export const ALERT_DETAILS_STARTED = "ALERT_DETAILS_STARTED";
export const ALERT_DETAILS_FAILED = "ALERT_DETAILS_FAILED";

export const ALERT_FETCH_STARTED = "ALERT_FETCH_STARTED";
export const ALERT_FETCH_SUCCESS = "ALERT_FETCH_SUCCESS";
export const ALERT_FETCH_FAILED = "ALERT_FETCH_FAILED";

export const ALERT_UPDATE_STARTED = "ALERT_UPDATE_STARTED";
export const ALERT_UPDATE_SUCCESS = "ALERT_UPDATE_SUCCESS";
export const ALERT_UPDATE_FAILED = "ALERT_UPDATE_FAILED";

export const ALERT_DELETE_STARTED = "ALERT_DELETE_STARTED";
export const ALERT_DELETE_SUCCESS = "ALERT_DELETE_SUCCESS";
export const ALERT_DELETE_FAILED = "ALERT_DELETE_FAILED";
